language: bash
dist: trusty
sudo: required

branches:
  only:
    - master

env:
  global:
    - BUILD_DATE="`date -u +%Y-%m-%dT%H:%M:%SZ`"
    - BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
    - DOCKER_DESCRIPTION="ubuntu base image"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="ubuntu"
    - DOCKER_URL="https://www.ubuntu.com/"
    - SCHEMA_VERSION="1.0"
    - VCS_REF="`git rev-parse --short HEAD`"
    - VCS_URL="`git remote get-url origin | head -c-5`"

  matrix:
    - DOCKER_TAG="rolling"
      DOCKER_VERSION="`curl -s https://raw.githubusercontent.com/tianon/docker-brew-ubuntu-core/master/rolling`"

before_install:
  - sudo apt-get update -q
  - sudo apt-get upgrade -q -y
  - docker version
  
install:
  - docker run --name ubuntu -it -e DEBIAN_FRONTEND=noninteractive ubuntu:rolling /bin/bash -c "
    apt-get update ;
    apt-get upgrade -y ;
    apt-get install -y --no-install-recommends ca-certificates
      curl
      gosu
      openssl
      tzdata ;
    apt-get autoremove -y --purge ;
    apt-get autoclean -y ;
    rm -rf /tmp/* ;
    rm -rf /var/lib/apt/lists/* ;
    exit "

script:
  - docker export -o ubuntu-${DOCKER_VERSION}-base.tar `docker ps -a | grep ubuntu  | awk -F ' ' {'print $1'}`
  - docker import ubuntu-${DOCKER_VERSION}-base.tar ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}

after_success:
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}

notifications:
  email:
    on_success: never
    on_failure: change
