dist: xenial
group: travis_latest

if: |
  branch = master
  AND ! commit_message =~ /readme.md/
  AND ! commit_message =~ /docker-compose.yml/
  OR type = cron

language: bash
sudo: required

services:
  - docker

env:

  global:
    - BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    - BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}"
    - DOCKER_DESCRIPTION="java base image"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="java"
    - DOCKER_URL="https://www.java.com/"
    - SCHEMA_VERSION="1.0"
    - UBUNTU_CODENAME="$(curl -ksSL https://raw.githubusercontent.com/tianon/docker-brew-ubuntu-core/master/rolling)"
    - VCS_REF="$(git rev-parse --short HEAD)"
    - VCS_URL="$(git remote get-url origin | head -c-5)"
    
  matrix:
    - DOCKER_TAG="8"
      DOCKER_VERSION="$(curl -ksSL https://packages.ubuntu.com/${UBUNTU_CODENAME}/openjdk-8-jre-headless | grep h1 | head -n 1 |awk -F ' ' {'print $3'} | cut -c 2- | rev | cut -c 2- | rev)"

before_install:
  - sudo /sbin/sysctl -w net.ipv4.conf.all.forwarding=1
  - sudo bash travis/docker.sh

install:

before_script:
  - sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' docker/Dockerfile*

script:
  - sudo bash travis/build.sh
  - sudo bash travis/deploy.sh

after_success:
  - sudo bash travis/trigger.sh

notifications:
  email:
    on_success: never
    on_failure: change
