language: bash
dist: trusty
group: travis_latest
sudo: required

addons:
  apt:
    packages:
      - docker-ce

branches:
  only:
    - master

stage: build

env:
  global:
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="java"
  matrix:
    - DOCKER_TAG="8"
    - DOCKER_TAG="11"

before_install:
  - docker version
  - sudo /sbin/sysctl -w net.ipv4.conf.all.forwarding=1

install:

before_script:
  - sed -i -e "/^$/d" -e "s/^[ \t]*//" -e "/^#/d" java${DOCKER_TAG}/Dockerfile

script:
  - docker build --tag ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG} --pull java${DOCKER_TAG}/.

after_success:
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}

jobs:
  include:
    - stage: trigger
      env: DOCKER_TAG=none
      before_install: skip
      install: skip
      before_script: skip
      script:
      # Trigger airsonic_docker build
      - >
        curl -X POST
        -H "Content-Type: application/json"
        -H "Travis-API-Version: 3"
        -H "Accept: application/json"
        -H "Authorization: token ${TRAVIS_API_TOKEN}"
        -d '{"request": {"message": "Push from stlouisn/java", "branch": "master"}}'
        'https://api.travis-ci.org/repo/stlouisn%2Fairsonic_docker/requests'
      # Trigger unifi_docker build
      - >
        curl -X POST
        -H "Content-Type: application/json"
        -H "Travis-API-Version: 3"
        -H "Accept: application/json"
        -H "Authorization: token ${TRAVIS_API_TOKEN}"
        -d '{"request": {"message": "Push from stlouisn/java", "branch": "master"}}'
        'https://api.travis-ci.org/repo/stlouisn%2Funifi_docker/requests'
      after_success: skip

notifications:
  email:
    on_success: never
    on_failure: change
