language: bash
dist: trusty
group: travis_latest
sudo: required

addons:
  apt:
    packages:
      - docker-ce

branches:
  only:
    - master

env:
  global:
    - BUILD_DATE="`date -u +%Y-%m-%dT%H:%M:%SZ`"
    - BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
    - DISTRIB_ID="`(docker pull stlouisn/ubuntu:rolling && docker run -it --rm stlouisn/ubuntu:rolling /bin/bash -c 'cat /etc/lsb-release') | grep DISTRIB_ID | awk -F '=' {'print $2'}`"
    - DISTRIB_RELEASE="`(docker pull stlouisn/ubuntu:rolling && docker run -it --rm stlouisn/ubuntu:rolling /bin/bash -c 'cat /etc/lsb-release') | grep DISTRIB_RELEASE | awk -F '=' {'print $2'}`"
    - DISTRIB_CODENAME="`(docker pull stlouisn/ubuntu:rolling && docker run -it --rm stlouisn/ubuntu:rolling /bin/bash -c 'cat /etc/lsb-release') | grep DISTRIB_CODENAME | awk -F '=' {'print $2'}`"
    - DOCKER_DESCRIPTION="java base image"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="java"
    - DOCKER_URL="http://openjdk.java.net/"
    - SCHEMA_VERSION="1.0"
    - VCS_REF="`git rev-parse --short HEAD`"
    - VCS_URL="`git remote get-url origin | head -c-5`"
  matrix:
    - DOCKER_TAG="default"
      DOCKER_VERSION="`curl -s https://raw.githubusercontent.com/tianon/docker-brew-ubuntu-core/master/rolling`"
    - DOCKER_TAG="8"
      DOCKER_VERSION="`curl -s https://packages.ubuntu.com/artful/amd64/openjdk-8-jre-headless/download | grep 'Download Page' | awk -F '_' {'print $2'} | awk -F '-' {'print $1'}`"
    - DOCKER_TAG="9"
      DOCKER_VERSION="`curl -s https://raw.githubusercontent.com/tianon/docker-brew-ubuntu-core/master/rolling`"

before_install:
  - docker version

install:
  #- if tag=8 then sed default openjdk-8

before_script:
  - sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' Dockerfile

script:
  - docker build --tag ${DOCKER_USERNAME}/${DOCKER_NAME}:base --pull .
  - docker run --name ubuntu -it ${DOCKER_USERNAME}/${DOCKER_NAME}:base /bin/bash -c exit
  - docker export -o ubuntu-${DOCKER_VERSION}-base.tar `docker ps -a | grep ubuntu  | awk -F ' ' {'print $1'}`
  - docker import ubuntu-${DOCKER_VERSION}-base.tar --change "LABEL org.label-schema.build-date='$BUILD_DATE' org.label-schema.build-number='$BUILD_NUMBER' org.label-schema.description='$DOCKER_DESCRIPTION' org.label-schema.maintainer='$DOCKER_MAINTAINER' org.label-schema.name='$DOCKER_NAME' org.label-schema.url='$DOCKER_URL' org.label-schema.version='$DOCKER_VERSION' org.label-schema.schema-version='$SCHEMA_VERSION' org.label-schema.vcs-ref='$VCS_REF' org.label-schema.vcs-url='$VCS_URL'" ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}

after_success:
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}

notifications:
  email:
    on_success: never
    on_failure: change
